<script src="{{ asset('assets') }}/js/jquery.js"></script>
<script src="{{ asset('assets') }}/js/popper.min.js"></script>
<script src="{{ asset('assets') }}/js/chosen.min.js"></script>
<script src="{{ asset('assets') }}/js/bootstrap.min.js"></script>
<script src="{{ asset('assets') }}/js/jquery.fancybox.js"></script>
<script src="{{ asset('assets') }}/js/jquery.modal.min.js"></script>
<script src="{{ asset('assets') }}/js/mmenu.polyfills.js"></script>
<script src="{{ asset('assets') }}/js/mmenu.js"></script>
<script src="{{ asset('assets') }}/js/appear.js"></script>
<script src="{{ asset('assets') }}/js/anm.min.js"></script>
<script src="{{ asset('assets') }}/js/owl.js"></script>
<script src="{{ asset('assets') }}/js/wow.js"></script>
<script src="{{ asset('assets') }}/js/script.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
